---
title: "100 Days of Code Day 2"
author: "Subah Nuzhat"
date: "2023-07-23"
output: html_document
---
### Day 2 Targets:
* Control Structures
* Functions
* Booleans

Resources used:
* https://cran.r-project.org/doc/contrib/Paradis-rdebuts_en.pdf
* https://www.youtube.com/watch?v=bldXk_mVMuI&list=PLhR2Go-lh6X4fCAa3c_TBAjZD5A25s7fo&index=3

<br>


### IF/ELSE
if(statement){
  expression
}
```{r}
a <- 12 
b <- 29
if(a>b){ 
  c <- a+1
} else if (a==b){
 a = 0 
}else {
  c<- NaN
}

```
Use multiple statements in one if clause
```{r}
ten = 1:10
ten > 5
all(ten > 5)
any(ten > 5)
#and
if(length(ten)==10 && any(ten > 5)){
  print("There are 10 items in ten and at least one item is greater than 10")
}

#OR
if(length(ten)==10 || any(ten > 5)){
  print("There are 10 items in ten and at least one item is greater than 10")
}
```
Special control structures
```{r}
a <- -1
if (a < 0) warning("a needs to be bigger")

b <- 100
if (b>500) stop("this is a sign to stop the loop")

tryCatch(a>19, error = function(e){print("try to recover")},finally = print("hello"))
```

### SWITCH STATEMENTS
```{r}
```


### FOR LOOPS
```{r}

for(a in 1:5){
  print('this is a number')
  print(a)
  print("subtract 1")
  print(a - 1)
}
```
### While loop
```{r}
num = 200

while (num < 220){
  print("before adding 5")
  num <- num + 5
  print("After adding 5")
  print(num)}

```

### Function
```{r}

say_hello <- function (name){
  print("Hello")
}
say_hello()
```
```{r}
edit <- function(num=0){
  new_num <- (num + 3)**2
  return (new_num)
}

edit()
edit(3)
```

